import { Color, Duration, FontWeight, Insets, OneLineText, Pixel, Point } from './domain/base';
import { Shape } from './domain';

export declare const DEFAULT_ZOOM = 1;
export declare const DEFAULT_VIEWPORT_CENTER: Point<Pixel>;
export declare const DEFAULT_CONTENT_INSETS: Insets<Pixel>;
export declare const DEFAULT_EDGE_SMOOTH_RADIUS: Pixel;
export declare const DEFAULT_CLASS_WIDTH: Pixel;
export declare const DEFAULT_CLASS_MARGIN_TOP: Pixel;
export declare const DEFAULT_CLASS_MARGIN_BOTTOM: Pixel;
export declare const DEFAULT_CLASS_MARGIN_LEFT: Pixel;
export declare const DEFAULT_CLASS_MARGIN_RIGHT: Pixel;
export declare const DEFAULT_CLASS_TITLE_LINE_HEIGHT: Pixel;
export declare const DEFAULT_CLASS_TITLE_FONT_SIZE: Pixel;
export declare const DEFAULT_CLASS_TITLE_FONT_WEIGHT: FontWeight;
export declare const DEFAULT_CLASS_SPLITTER_PADDING_LEFT: Pixel;
export declare const DEFAULT_CLASS_SPLITTER_PADDING_RIGHT: Pixel;
export declare const DEFAULT_CLASS_SPLITTER_PADDING_TOP: Pixel;
export declare const DEFAULT_CLASS_SPLITTER_PADDING_BOTTOM: Pixel;
export declare const DEFAULT_CLASS_SPLITTER_COLOR: Color;
export declare const DEFAULT_CLASS_SPLITTER_LENGTH: Pixel;
export declare const DEFAULT_CLASS_NAME: OneLineText;
export declare const DEFAULT_CLASS_DEPRECATION = false;
export declare const DEFAULT_CLASS_SHAPE: Shape;
export declare const DEFAULT_CLASS_PORT_WIDTH: Pixel;
export declare const DEFAULT_CLASS_ROUND_RECT_RADIUS: Pixel;
export declare const DEFAULT_CLASS_SHAPE_STROKE: Color;
export declare const DEFAULT_CLASS_SHAPE_STROKE_WIDTH: Pixel;
export declare const DEFAULT_CLASS_SHAPE_FILL_COLOR: Color;
export declare const DEFAULT_CLASS_SHAPE_SELECTION_FILL_COLOR: Color;
export declare const DEFAULT_CLASS_HEADER_HEIGHT: Pixel;
export declare const DEFAULT_LEAF_PROPERTY_NAME: OneLineText;
export declare const DEFAULT_LEAF_PROPERTY_TYPE: OneLineText;
export declare const DEFAULT_LEAF_PROPERTY_TYPE_DEPRECATION = false;
export declare const DEFAULT_LEAF_PROPERTY_REQUIRED = false;
export declare const DEFAULT_LEAF_PROPERTY_DEPRECATION = false;
export declare const DEFAULT_LEAF_PROPERTY_LINE_HEIGHT: Pixel;
export declare const DEFAULT_LEAF_PROPERTY_FONT_SIZE: Pixel;
export declare const DEFAULT_LEAF_PROPERTY_FONT_WEIGHT: FontWeight;
export declare const DEFAULT_LEAF_PROPERTY_PORT_WIDTH: Pixel;
export declare const DEFAULT_LEAF_PROPERTY_NAME_FONT_COLOR: Color;
export declare const DEFAULT_LEAF_PROPERTY_REQUIRED_FONT_COLOR: Color;
export declare const DEFAULT_LEAF_PROPERTY_TYPE_FONT_COLOR: Color;
export declare const DEFAULT_LEAF_PROPERTY_SELECTION_FILL_COLOR: Color;
export declare const DEFAULT_LEAF_PROPERTY_SEPARATOR_LENGTH: Pixel;
export declare const DEFAULT_LEAF_PROPERTY_REQUIRED_CHARACTER: OneLineText;
export declare const DEFAULT_PROPERTIES_GROUP_NAME = "unknown";
export declare const DEFAULT_PROPERTIES_GROUP_DEPRECATION = false;
export declare const DEFAULT_PROPERTIES_GROUP_TITLE_HEIGHT: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_FONT_SIZE: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_FONT_WEIGHT: FontWeight;
export declare const DEFAULT_PROPERTIES_GROUP_FONT_COLOR: Color;
export declare const DEFAULT_PROPERTIES_GROUP_ICON_SIZE: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_ICON_PADDING_LEFT: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_ICON_TO_NAME_SEPARATOR_LENGTH: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_TITLE_TO_CHILDREN_SEPARATOR_LENGTH: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_TITLE_PADDING_RIGHT: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_PORT_WIDTH: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_SPLITTER_PADDING_LEFT: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_SPLITTER_PADDING_RIGHT: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_SPLITTER_PADDING_TOP: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_SPLITTER_PADDING_BOTTOM: Pixel;
export declare const DEFAULT_PROPERTIES_GROUP_SELECTION_FILL_COLOR: Color;
export declare const DEFAULT_INCLUDE_PROPERTIES_GROUP_RELATION_PRIMARY = true;
export declare const DEFAULT_INCLUDE_PROPERTIES_GROUP_RELATION_STROKE_COLOR: Color;
export declare const DEFAULT_INCLUDE_PROPERTIES_GROUP_RELATION_SELECTION_STROKE_COLOR: Color;
export declare const DEFAULT_INCLUDE_PROPERTIES_GROUP_RELATION_STROKE_WIDTH: Pixel;
export declare const DEFAULT_INCLUDE_PROPERTIES_GROUP_RELATION_SELECTION_STROKE_WIDTH: Pixel;
export declare const DEFAULT_PROPERTY_TO_CLASS_RELATION_PRIMARY = true;
export declare const DEFAULT_PROPERTY_TO_CLASS_RELATION_STROKE_COLOR: Color;
export declare const DEFAULT_PROPERTY_TO_CLASS_RELATION_SELECTION_STROKE_COLOR: Color;
export declare const DEFAULT_PROPERTY_TO_CLASS_RELATION_STROKE_WIDTH: Pixel;
export declare const DEFAULT_PROPERTY_TO_CLASS_RELATION_SELECTION_STROKE_WIDTH: Pixel;
export declare const DEFAULT_ANIMATION_DURATION: Duration;
export declare const DEFAULT_ELLIPSIS_CHARACTER = "\u2026";
export declare const DEFAULT_FULL_TEXT_LABEL_ROUND_RECT_RADIUS: Pixel;
